import { Theme } from '../types';

export const themes: Theme[] = [
    {
        name: 'Royal Gold Premium',
        id: 'royal-gold',
        colors: {
            primary: '#D4AF37',
            secondary: '#1A1A1A',
            accent: '#FFD700',
            background: '#0A0A0A',
            surface: '#1F1F1F',
            card: '#1F1F1F',
            text: '#FFFFFF',
            textSecondary: '#B8B8B8',
            textOnPrimary: '#1A1A1A',
            border: '#333333',
            success: '#10B981',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#3B82F6',
        },
        effects: {
            cardBackground: 'rgba(31, 31, 31, 0.9)',
            cardBorder: 'rgba(212, 175, 55, 0.3)',
            cardShadow: 'rgba(212, 175, 55, 0.15)',
            glassBackground: 'rgba(31, 31, 31, 0.7)',
            glassBlur: '20',
            buttonGradient: ['#D4AF37', '#FFD700'],
            hoverTransform: '4',
        },
    },
    {
        name: 'Material-You Soft Pastel',
        id: 'material-pastel',
        colors: {
            primary: '#A78BFA',
            secondary: '#F3E8FF',
            accent: '#C084FC',
            background: '#FAF5FF',
            surface: '#FFFFFF',
            card: '#FFFFFF',
            text: '#1F2937',
            textSecondary: '#6B7280',
            textOnPrimary: '#FFFFFF',
            border: '#E9D5FF',
            success: '#34D399',
            warning: '#FBBF24',
            error: '#F87171',
            info: '#60A5FA',
        },
        effects: {
            cardBackground: '#FFFFFF',
            cardBorder: '#E9D5FF',
            cardShadow: 'rgba(167, 139, 250, 0.12)',
            glassBackground: 'rgba(255, 255, 255, 0.8)',
            glassBlur: '16',
            buttonGradient: ['#A78BFA', '#C084FC'],
            hoverTransform: '2',
        },
    },
    {
        name: 'Ultra-Neumorphism Light',
        id: 'neumorphism-light',
        colors: {
            primary: '#6366F1',
            secondary: '#E0E7FF',
            accent: '#818CF8',
            background: '#E5E7EB',
            surface: '#F3F4F6',
            card: '#F3F4F6',
            text: '#111827',
            textSecondary: '#6B7280',
            textOnPrimary: '#FFFFFF',
            border: '#D1D5DB',
            success: '#10B981',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#3B82F6',
        },
        effects: {
            cardBackground: '#F3F4F6',
            cardBorder: '#F3F4F6', // 'none' in web, approximated for mobile
            cardShadow: 'rgba(0,0,0,0.1)', // Complex shadow emulation simplified
            glassBackground: '#F3F4F6',
            glassBlur: '0',
            buttonGradient: ['#6366F1', '#818CF8'],
            hoverTransform: '2',
        },
    },
    {
        name: 'Dark + Neon Blue',
        id: 'dark-neon',
        colors: {
            primary: '#00F0FF',
            secondary: '#0A0E27',
            accent: '#00D9FF',
            background: '#050814',
            surface: '#0F1629',
            card: '#0F1629',
            text: '#FFFFFF',
            textSecondary: '#8B92B0',
            textOnPrimary: '#050814',
            border: '#1E293B',
            success: '#00FF88',
            warning: '#FFB800',
            error: '#FF0055',
            info: '#00F0FF',
        },
        effects: {
            cardBackground: 'rgba(15, 22, 41, 0.9)',
            cardBorder: 'rgba(0, 240, 255, 0.3)',
            cardShadow: 'rgba(0, 240, 255, 0.2)',
            glassBackground: 'rgba(15, 22, 41, 0.7)',
            glassBlur: '20',
            buttonGradient: ['#00F0FF', '#00D9FF'],
            hoverTransform: '3',
        },
    },
    {
        name: 'Ultra-Gradient Fintech',
        id: 'gradient-fintech',
        colors: {
            primary: '#8B5CF6',
            secondary: '#3B82F6',
            accent: '#06B6D4',
            background: '#0F172A',
            surface: '#1E293B',
            card: '#1E293B',
            text: '#F8FAFC',
            textSecondary: '#94A3B8',
            textOnPrimary: '#FFFFFF',
            border: '#334155',
            success: '#10B981',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#06B6D4',
        },
        effects: {
            cardBackground: 'rgba(30, 41, 59, 0.9)',
            cardBorder: 'rgba(139, 92, 246, 0.3)',
            cardShadow: 'rgba(139, 92, 246, 0.2)',
            glassBackground: 'rgba(30, 41, 59, 0.7)',
            glassBlur: '24',
            buttonGradient: ['#8B5CF6', '#3B82F6', '#06B6D4'],
            hoverTransform: '4',
        },
    },
    {
        name: 'Minimal Corporate White',
        id: 'minimal-white',
        colors: {
            primary: '#0F172A',
            secondary: '#475569',
            accent: '#334155',
            background: '#FFFFFF',
            surface: '#F8FAFC',
            card: '#F8FAFC',
            text: '#0F172A',
            textSecondary: '#64748B',
            textOnPrimary: '#FFFFFF',
            border: '#E2E8F0',
            success: '#059669',
            warning: '#D97706',
            error: '#DC2626',
            info: '#0284C7',
        },
        effects: {
            cardBackground: '#FFFFFF',
            cardBorder: '#E2E8F0',
            cardShadow: 'rgba(0, 0, 0, 0.05)',
            glassBackground: '#FFFFFF',
            glassBlur: '0',
            buttonGradient: ['#0F172A', '#334155'],
            hoverTransform: '2',
        },
    },
    {
        name: 'Glassmorphism Frost',
        id: 'glass-frost',
        colors: {
            primary: '#3B82F6',
            secondary: '#60A5FA',
            accent: '#93C5FD',
            background: '#667EEA',
            surface: 'rgba(255, 255, 255, 0.1)',
            card: 'rgba(255, 255, 255, 0.1)',
            text: '#FFFFFF',
            textSecondary: '#E0E7FF',
            textOnPrimary: '#FFFFFF',
            border: 'rgba(255, 255, 255, 0.2)',
            success: '#34D399',
            warning: '#FBBF24',
            error: '#F87171',
            info: '#60A5FA',
        },
        effects: {
            cardBackground: 'rgba(255, 255, 255, 0.1)',
            cardBorder: 'rgba(255, 255, 255, 0.2)',
            cardShadow: 'rgba(0, 0, 0, 0.1)',
            glassBackground: 'rgba(255, 255, 255, 0.15)',
            glassBlur: '30',
            buttonGradient: ['rgba(255, 255, 255, 0.2)', 'rgba(255, 255, 255, 0.1)'],
            hoverTransform: '3',
        },
    },
    {
        name: 'Mint Green Finance',
        id: 'mint-green',
        colors: {
            primary: '#10B981',
            secondary: '#059669',
            accent: '#34D399',
            background: '#F0FDF4',
            surface: '#FFFFFF',
            card: '#FFFFFF',
            text: '#064E3B',
            textSecondary: '#047857',
            textOnPrimary: '#FFFFFF',
            border: '#A7F3D0',
            success: '#10B981',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#06B6D4',
        },
        effects: {
            cardBackground: '#FFFFFF',
            cardBorder: '#A7F3D0',
            cardShadow: 'rgba(16, 185, 129, 0.12)',
            glassBackground: 'rgba(255, 255, 255, 0.9)',
            glassBlur: '16',
            buttonGradient: ['#10B981', '#059669'],
            hoverTransform: '2',
        },
    },
    {
        name: 'Royal Maroon + Cream',
        id: 'royal-maroon',
        colors: {
            primary: '#881337',
            secondary: '#9F1239',
            accent: '#BE123C',
            background: '#FFF1F2',
            surface: '#FFFBEB',
            card: '#FFFBEB',
            text: '#450A0A',
            textSecondary: '#7F1D1D',
            textOnPrimary: '#FFF1F2',
            border: '#FECDD3',
            success: '#059669',
            warning: '#D97706',
            error: '#DC2626',
            info: '#0284C7',
        },
        effects: {
            cardBackground: '#FFFBEB', // Simplified gradient
            cardBorder: '#FECDD3',
            cardShadow: 'rgba(136, 19, 55, 0.15)',
            glassBackground: 'rgba(255, 251, 235, 0.8)',
            glassBlur: '20',
            buttonGradient: ['#881337', '#9F1239'],
            hoverTransform: '3',
        },
    },
    {
        name: 'Deep Ocean Blue',
        id: 'ocean-blue',
        colors: {
            primary: '#0EA5E9',
            secondary: '#0284C7',
            accent: '#38BDF8',
            background: '#0C1A2E',
            surface: '#1E3A5F',
            card: '#1E3A5F',
            text: '#F0F9FF',
            textSecondary: '#BAE6FD',
            textOnPrimary: '#FFFFFF',
            border: '#075985',
            success: '#22C55E',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#38BDF8',
        },
        effects: {
            cardBackground: 'rgba(30, 58, 95, 0.9)',
            cardBorder: 'rgba(14, 165, 233, 0.3)',
            cardShadow: 'rgba(14, 165, 233, 0.25)',
            glassBackground: 'rgba(30, 58, 95, 0.7)',
            glassBlur: '24',
            buttonGradient: ['#0EA5E9', '#38BDF8'],
            hoverTransform: '4',
        },
    },
    {
        name: 'Emerald Wealth',
        id: 'emerald-wealth',
        colors: {
            primary: '#047857',
            secondary: '#065F46',
            accent: '#10B981',
            background: '#ECFDF5',
            surface: '#FFFFFF',
            card: '#FFFFFF',
            text: '#064E3B',
            textSecondary: '#047857',
            textOnPrimary: '#FFFFFF',
            border: '#D1FAE5',
            success: '#10B981',
            warning: '#F59E0B',
            error: '#DC2626',
            info: '#0284C7',
        },
        effects: {
            cardBackground: '#FFFFFF',
            cardBorder: '#D1FAE5',
            cardShadow: 'rgba(4, 120, 87, 0.15)',
            glassBackground: 'rgba(255, 255, 255, 0.85)',
            glassBlur: '16',
            buttonGradient: ['#047857', '#10B981'],
            hoverTransform: '2',
        },
    },
    {
        name: 'Midnight Purple Pro',
        id: 'midnight-purple',
        colors: {
            primary: '#7C3AED',
            secondary: '#6D28D9',
            accent: '#A78BFA',
            background: '#1E1B2E',
            surface: '#2D2A3F',
            card: '#2D2A3F',
            text: '#EDE9FE',
            textSecondary: '#C4B5FD',
            textOnPrimary: '#FFFFFF',
            border: '#4C1D95',
            success: '#10B981',
            warning: '#FBBF24',
            error: '#F87171',
            info: '#60A5FA',
        },
        effects: {
            cardBackground: 'rgba(45, 42, 63, 0.9)',
            cardBorder: 'rgba(124, 58, 237, 0.4)',
            cardShadow: 'rgba(124, 58, 237, 0.3)',
            glassBackground: 'rgba(45, 42, 63, 0.75)',
            glassBlur: '20',
            buttonGradient: ['#7C3AED', '#A78BFA'],
            hoverTransform: '3',
        },
    },
    {
        name: 'Rose Gold Elite',
        id: 'rose-gold',
        colors: {
            primary: '#E11D48',
            secondary: '#BE123C',
            accent: '#FB7185',
            background: '#FFF1F2',
            surface: '#FFFFFF',
            card: '#FFFFFF',
            text: '#881337',
            textSecondary: '#9F1239',
            textOnPrimary: '#FFFFFF',
            border: '#FECDD3',
            success: '#059669',
            warning: '#D97706',
            error: '#DC2626',
            info: '#0284C7',
        },
        effects: {
            cardBackground: '#FFFFFF',
            cardBorder: '#FECDD3',
            cardShadow: 'rgba(225, 29, 72, 0.18)',
            glassBackground: 'rgba(255, 255, 255, 0.9)',
            glassBlur: '18',
            buttonGradient: ['#E11D48', '#FB7185'],
            hoverTransform: '2',
        },
    },
    {
        name: 'Slate Professional',
        id: 'slate-pro',
        colors: {
            primary: '#475569',
            secondary: '#334155',
            accent: '#64748B',
            background: '#F8FAFC',
            surface: '#FFFFFF',
            card: '#FFFFFF',
            text: '#0F172A',
            textSecondary: '#64748B',
            textOnPrimary: '#FFFFFF',
            border: '#E2E8F0',
            success: '#059669',
            warning: '#D97706',
            error: '#DC2626',
            info: '#0284C7',
        },
        effects: {
            cardBackground: '#FFFFFF',
            cardBorder: '#E2E8F0',
            cardShadow: 'rgba(15, 23, 42, 0.08)',
            glassBackground: 'rgba(255, 255, 255, 0.95)',
            glassBlur: '12',
            buttonGradient: ['#475569', '#64748B'],
            hoverTransform: '2',
        },
    },
    {
        name: 'Amber Sunset',
        id: 'amber-sunset',
        colors: {
            primary: '#F59E0B',
            secondary: '#D97706',
            accent: '#FBBF24',
            background: '#FFFBEB',
            surface: '#FFFFFF',
            card: '#FFFFFF',
            text: '#78350F',
            textSecondary: '#92400E',
            textOnPrimary: '#78350F',
            border: '#FED7AA',
            success: '#059669',
            warning: '#F59E0B',
            error: '#DC2626',
            info: '#0284C7',
        },
        effects: {
            cardBackground: '#FFFFFF',
            cardBorder: '#FED7AA',
            cardShadow: 'rgba(245, 158, 11, 0.15)',
            glassBackground: 'rgba(255, 255, 255, 0.88)',
            glassBlur: '16',
            buttonGradient: ['#F59E0B', '#FBBF24'],
            hoverTransform: '2',
        },
    },
    {
        name: 'Carbon Black Premium',
        id: 'carbon-black',
        colors: {
            primary: '#FFFFFF',
            secondary: '#E5E5E5',
            accent: '#A3A3A3',
            background: '#0A0A0A',
            surface: '#171717',
            card: '#171717',
            text: '#FAFAFA',
            textSecondary: '#A3A3A3',
            textOnPrimary: '#0A0A0A',
            border: '#262626',
            success: '#22C55E',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#3B82F6',
        },
        effects: {
            cardBackground: 'rgba(23, 23, 23, 0.9)',
            cardBorder: '#262626',
            cardShadow: 'rgba(0, 0, 0, 0.6)',
            glassBackground: 'rgba(23, 23, 23, 0.8)',
            glassBlur: '24',
            buttonGradient: ['#404040', '#171717'],
            hoverTransform: '3',
        },
    },
    {
        name: 'Teal Finance Pro',
        id: 'teal-finance',
        colors: {
            primary: '#14B8A6',
            secondary: '#0D9488',
            accent: '#2DD4BF',
            background: '#F0FDFA',
            surface: '#FFFFFF',
            card: '#FFFFFF',
            text: '#134E4A',
            textSecondary: '#0F766E',
            textOnPrimary: '#FFFFFF',
            border: '#99F6E4',
            success: '#10B981',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#06B6D4',
        },
        effects: {
            cardBackground: '#FFFFFF',
            cardBorder: '#99F6E4',
            cardShadow: 'rgba(20, 184, 166, 0.15)',
            glassBackground: 'rgba(255, 255, 255, 0.9)',
            glassBlur: '16',
            buttonGradient: ['#14B8A6', '#2DD4BF'],
            hoverTransform: '2',
        },
    },
    {
        name: 'Indigo Corporate',
        id: 'indigo-corporate',
        colors: {
            primary: '#4F46E5',
            secondary: '#4338CA',
            accent: '#6366F1',
            background: '#EEF2FF',
            surface: '#FFFFFF',
            card: '#FFFFFF',
            text: '#312E81',
            textSecondary: '#4338CA',
            textOnPrimary: '#FFFFFF',
            border: '#C7D2FE',
            success: '#059669',
            warning: '#D97706',
            error: '#DC2626',
            info: '#0284C7',
        },
        effects: {
            cardBackground: '#FFFFFF',
            cardBorder: '#C7D2FE',
            cardShadow: 'rgba(79, 70, 229, 0.15)',
            glassBackground: 'rgba(255, 255, 255, 0.92)',
            glassBlur: '16',
            buttonGradient: ['#4F46E5', '#6366F1'],
            hoverTransform: '2',
        },
    },
    {
        name: 'Crimson Executive',
        id: 'crimson-executive',
        colors: {
            primary: '#DC2626',
            secondary: '#B91C1C',
            accent: '#EF4444',
            background: '#1F2937',
            surface: '#374151',
            card: '#374151',
            text: '#F9FAFB',
            textSecondary: '#D1D5DB',
            textOnPrimary: '#FFFFFF',
            border: '#4B5563',
            success: '#10B981',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#3B82F6',
        },
        effects: {
            cardBackground: 'rgba(55, 65, 81, 0.9)',
            cardBorder: 'rgba(220, 38, 38, 0.3)',
            cardShadow: 'rgba(220, 38, 38, 0.25)',
            glassBackground: 'rgba(55, 65, 81, 0.75)',
            glassBlur: '20',
            buttonGradient: ['#DC2626', '#EF4444'],
            hoverTransform: '3',
        },
    },
    {
        name: 'Solar Orange Modern',
        id: 'solar-orange',
        colors: {
            primary: '#EA580C',
            secondary: '#C2410C',
            accent: '#FB923C',
            background: '#1F2937',
            surface: '#374151',
            card: '#374151',
            text: '#F9FAFB',
            textSecondary: '#D1D5DB',
            textOnPrimary: '#FFFFFF',
            border: '#4B5563',
            success: '#10B981',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#3B82F6',
        },
        effects: {
            cardBackground: 'rgba(55, 65, 81, 0.9)',
            cardBorder: 'rgba(234, 88, 12, 0.3)',
            cardShadow: 'rgba(234, 88, 12, 0.2)',
            glassBackground: 'rgba(55, 65, 81, 0.8)',
            glassBlur: '20',
            buttonGradient: ['#EA580C', '#FB923C'],
            hoverTransform: '3',
        },
    },
];

export const getThemeById = (id: string): Theme => {
    return themes.find((theme) => theme.id === id) || themes[0];
};
