import { Ticket, TicketMessage, TeamMember, Client, RiskProfile, NewsItem, OrganizationRequest, ServiceRequest, CustomerMapping, License } from '../types';

export const mockServiceProviders = [
    { id: '1', name: 'John Smith' },
    { id: '2', name: 'Sarah Johnson' },
    { id: '3', name: 'Michael Brown' },
    { id: '4', name: 'Emily Davis' },
    { id: '5', name: 'Michael Roberts' },
    { id: '6', name: 'Jennifer Davis' },
];

export const mockReferralPartners = [
    { id: '1', name: 'James Wilson' },
    { id: '2', name: 'Linda Parker' },
    { id: '3', name: 'Robert Thompson' },
    { id: '4', name: 'Sandra Martinez' },
];

export const mockClients: Client[] = [
    {
        id: '1',
        name: 'John Anderson',
        email: 'john.anderson@email.com',
        phone: '+1 (555) 123-4567',
        role: 'Premium Client',
        status: 'active',
        assignedSP: 'Sarah Johnson',
        referralPartner: 'James Wilson',
        netWorth: 2500000,
        services: ['1', '2', '7'],
    },
    {
        id: '2',
        name: 'Emily Chen',
        email: 'emily.chen@email.com',
        phone: '+1 (555) 234-5678',
        role: 'Standard Client',
        status: 'active',
        assignedSP: 'John Smith',
        referralPartner: 'Linda Parker',
        netWorth: 850000,
        services: ['3', '4'],
    },
    {
        id: '3',
        name: 'Robert Martinez',
        email: 'robert.martinez@email.com',
        phone: '+1 (555) 345-6789',
        role: 'Premium Client',
        status: 'pending',
        assignedSP: 'Michael Brown',
        referralPartner: 'James Wilson',
        netWorth: 4200000,
        services: ['1', '5', '8'],
    },
    {
        id: '4',
        name: 'Linda Wilson',
        email: 'linda.wilson@email.com',
        phone: '+1 (555) 456-7890',
        role: 'Standard Client',
        status: 'active',
        assignedSP: 'Emily Davis',
        referralPartner: 'None',
        netWorth: 500000,
        services: ['2', '6'],
    },
    {
        id: '5',
        name: 'David Thompson',
        email: 'david.thompson@email.com',
        phone: '+1 (555) 567-8901',
        role: 'Premium Client',
        status: 'inactive',
        assignedSP: 'Sarah Johnson',
        referralPartner: 'Robert Thompson',
        netWorth: 1200000,
        services: ['1', '3'],
    },
    {
        id: '6',
        name: 'Sarah Parker',
        email: 'sarah.parker@email.com',
        phone: '+1 (555) 678-9012',
        role: 'Standard Client',
        status: 'active',
        assignedSP: 'John Smith',
        referralPartner: 'Sandra Martinez',
        netWorth: 750000,
        services: ['4', '9'],
    },
    {
        id: '7',
        name: 'Michael Davis',
        email: 'michael.davis@email.com',
        phone: '+1 (555) 789-0123',
        role: 'Premium Client',
        status: 'active',
        assignedSP: 'Michael Brown',
        referralPartner: 'James Wilson',
        netWorth: 3100000,
        services: ['2', '7', '10'],
    },
    {
        id: '8',
        name: 'Jennifer Brown',
        email: 'jennifer.brown@email.com',
        phone: '+1 (555) 890-1234',
        role: 'Standard Client',
        status: 'pending',
        assignedSP: 'Emily Davis',
        referralPartner: 'Linda Parker',
        netWorth: 450000,
        services: ['5', '6'],
    },
    {
        id: '9',
        name: 'William Roberts',
        email: 'william.roberts@email.com',
        phone: '+1 (555) 901-2345',
        role: 'Premium Client',
        status: 'active',
        assignedSP: 'Sarah Johnson',
        referralPartner: 'Robert Thompson',
        netWorth: 1800000,
        services: ['1', '8'],
    },
    {
        id: '10',
        name: 'Elizabeth Miller',
        email: 'elizabeth.miller@email.com',
        phone: '+1 (555) 012-3456',
        role: 'Standard Client',
        status: 'active',
        assignedSP: 'John Smith',
        referralPartner: 'None',
        netWorth: 950000,
        services: ['3', '7'],
    },
    {
        id: '11',
        name: 'Thomas White',
        email: 'thomas.white@email.com',
        phone: '+1 (555) 123-0011',
        role: 'Premium Client',
        status: 'active',
        assignedSP: 'Michael Roberts',
        referralPartner: 'Sandra Martinez',
        netWorth: 5500000,
        services: ['1', '2', '4', '8'],
    },
    {
        id: '12',
        name: 'Patricia Taylor',
        email: 'patricia.taylor@email.com',
        phone: '+1 (555) 123-0012',
        role: 'Standard Client',
        status: 'active',
        assignedSP: 'Jennifer Davis',
        referralPartner: 'Robert Thompson',
        netWorth: 620000,
        services: ['5', '9'],
    },
    {
        id: '13',
        name: 'Christopher Moore',
        email: 'chris.moore@email.com',
        phone: '+1 (555) 123-0013',
        role: 'Premium Client',
        status: 'pending',
        assignedSP: 'Sarah Johnson',
        referralPartner: 'James Wilson',
        netWorth: 2800000,
        services: ['2', '10'],
    },
    {
        id: '14',
        name: 'Barbara Jackson',
        email: 'barbara.j@email.com',
        phone: '+1 (555) 123-0014',
        role: 'Standard Client',
        status: 'active',
        assignedSP: 'Emily Davis',
        referralPartner: 'None',
        netWorth: 890000,
        services: ['3', '6'],
    },
    {
        id: '15',
        name: 'Daniel Anderson',
        email: 'daniel.a@email.com',
        phone: '+1 (555) 123-0015',
        role: 'Premium Client',
        status: 'active',
        assignedSP: 'John Smith',
        referralPartner: 'Linda Parker',
        netWorth: 3700000,
        services: ['1', '4', '7'],
    },
    {
        id: '16',
        name: 'Jessica Thomas',
        email: 'jessica.t@email.com',
        phone: '+1 (555) 123-0016',
        role: 'Standard Client',
        status: 'inactive',
        assignedSP: 'Michael Brown',
        referralPartner: 'Robert Thompson',
        netWorth: 410000,
        services: ['5', '8'],
    },
    {
        id: '17',
        name: 'Kevin Harris',
        email: 'kevin.h@email.com',
        phone: '+1 (555) 123-0017',
        role: 'Premium Client',
        status: 'active',
        assignedSP: 'Sarah Johnson',
        referralPartner: 'James Wilson',
        netWorth: 6800000,
        services: ['1', '2', '3', '10'],
    },
    {
        id: '18',
        name: 'Nancy Martin',
        email: 'nancy.m@email.com',
        phone: '+1 (555) 123-0018',
        role: 'Standard Client',
        status: 'pending',
        assignedSP: 'John Smith',
        referralPartner: 'Linda Parker',
        netWorth: 520000,
        services: ['4', '6', '9'],
    },
    {
        id: '19',
        name: 'Steven Garcia',
        email: 'steven.g@email.com',
        phone: '+1 (555) 123-0019',
        role: 'Premium Client',
        status: 'active',
        assignedSP: 'Emily Davis',
        referralPartner: 'Sandra Martinez',
        netWorth: 1500000,
        services: ['7', '8'],
    },
    {
        id: '20',
        name: 'Karen Young',
        email: 'karen.y@email.com',
        phone: '+1 (555) 123-0020',
        role: 'Standard Client',
        status: 'active',
        assignedSP: 'Michael Roberts',
        referralPartner: 'None',
        netWorth: 780000,
        services: ['2', '3', '5'],
    },
    {
        id: '21',
        name: 'Edward King',
        email: 'edward.k@email.com',
        phone: '+1 (555) 123-0021',
        role: 'Premium Client',
        status: 'active',
        assignedSP: 'Jennifer Davis',
        referralPartner: 'Robert Thompson',
        netWorth: 4200000,
        services: ['1', '6', '10'],
    },
    {
        id: '22',
        name: 'Ruth Lee',
        email: 'ruth.l@email.com',
        phone: '+1 (555) 123-0022',
        role: 'Standard Client',
        status: 'active',
        assignedSP: 'John Smith',
        referralPartner: 'James Wilson',
        netWorth: 640000,
        services: ['4', '9'],
    },
    {
        id: '23',
        name: 'Donald Scott',
        email: 'donald.s@email.com',
        phone: '+1 (555) 123-0023',
        role: 'Premium Client',
        status: 'pending',
        assignedSP: 'Michael Brown',
        referralPartner: 'Linda Parker',
        netWorth: 2900000,
        services: ['2', '7', '8'],
    },
    {
        id: '24',
        name: 'Helen Adams',
        email: 'helen.a@email.com',
        phone: '+1 (555) 123-0024',
        role: 'Standard Client',
        status: 'inactive',
        assignedSP: 'Emily Davis',
        referralPartner: 'None',
        netWorth: 310000,
        services: ['3', '5'],
    },
    {
        id: '25',
        name: 'George Baker',
        email: 'george.b@email.com',
        phone: '+1 (555) 123-0025',
        role: 'Premium Client',
        status: 'active',
        assignedSP: 'Sarah Johnson',
        referralPartner: 'Sandra Martinez',
        netWorth: 7500000,
        services: ['1', '2', '4', '10'],
    },
];

export const mockRiskProfiles: RiskProfile[] = [
    { id: '1', clientId: '1', clientName: 'John Anderson', score: 35, status: 'low', assignedSP: 'Sarah Johnson', referralPartner: 'James Wilson', lastAssessmentDate: '2025-11-15', nextReviewDate: '2026-11-15' },
    { id: '2', clientId: '2', clientName: 'Emily Chen', score: 65, status: 'medium', assignedSP: 'John Smith', referralPartner: 'Linda Parker', lastAssessmentDate: '2025-11-20', nextReviewDate: '2026-11-20' },
    { id: '3', clientId: '3', clientName: 'Robert Martinez', score: 85, status: 'high', assignedSP: 'Michael Brown', referralPartner: 'James Wilson', lastAssessmentDate: '2025-12-01', nextReviewDate: '2026-12-01' },
    { id: '4', clientId: '4', clientName: 'Linda Wilson', score: 45, status: 'medium', assignedSP: 'Emily Davis', referralPartner: 'None', lastAssessmentDate: '2025-11-10', nextReviewDate: '2026-11-10' },
    { id: '5', clientId: '5', clientName: 'David Thompson', score: 25, status: 'low', assignedSP: 'Sarah Johnson', referralPartner: 'Robert Thompson', lastAssessmentDate: '2025-12-05', nextReviewDate: '2026-12-05' },
    { id: '6', clientId: '6', clientName: 'Sarah Parker', score: 55, status: 'medium', assignedSP: 'John Smith', referralPartner: 'Sandra Martinez', lastAssessmentDate: '2025-12-08', nextReviewDate: '2026-12-08' },
    { id: '7', clientId: '7', clientName: 'Michael Davis', score: 75, status: 'high', assignedSP: 'Michael Brown', referralPartner: 'James Wilson', lastAssessmentDate: '2025-12-10', nextReviewDate: '2026-12-10' },
    { id: '8', clientId: '8', clientName: 'Jennifer Brown', score: 38, status: 'low', assignedSP: 'Emily Davis', referralPartner: 'Linda Parker', lastAssessmentDate: '2025-12-12', nextReviewDate: '2026-12-12' },
    { id: '9', clientId: '9', clientName: 'William Roberts', score: 72, status: 'high', assignedSP: 'Sarah Johnson', referralPartner: 'Robert Thompson', lastAssessmentDate: '2025-12-15', nextReviewDate: '2026-12-15' },
    { id: '10', clientId: '10', clientName: 'Elizabeth Miller', score: 58, status: 'medium', assignedSP: 'John Smith', referralPartner: 'None', lastAssessmentDate: '2025-12-20', nextReviewDate: '2026-12-20' },
    { id: '11', clientId: '11', clientName: 'Thomas White', score: 82, status: 'high', assignedSP: 'Michael Roberts', referralPartner: 'Sandra Martinez', lastAssessmentDate: '2026-01-05', nextReviewDate: '2027-01-05' },
    { id: '12', clientId: '12', clientName: 'Patricia Taylor', score: 32, status: 'low', assignedSP: 'Jennifer Davis', referralPartner: 'Robert Thompson', lastAssessmentDate: '2026-01-08', nextReviewDate: '2027-01-08' },
    { id: '13', clientId: '13', clientName: 'Christopher Moore', score: 48, status: 'medium', assignedSP: 'Sarah Johnson', referralPartner: 'James Wilson', lastAssessmentDate: '2026-01-10', nextReviewDate: '2027-01-10' },
    { id: '14', clientId: '14', clientName: 'Barbara Jackson', score: 64, status: 'medium', assignedSP: 'Emily Davis', referralPartner: 'None', lastAssessmentDate: '2026-01-12', nextReviewDate: '2027-01-12' },
    { id: '15', clientId: '15', clientName: 'Daniel Anderson', score: 76, status: 'high', assignedSP: 'John Smith', referralPartner: 'Linda Parker', lastAssessmentDate: '2026-01-15', nextReviewDate: '2027-01-15' },
    { id: '16', clientId: '16', clientName: 'Jessica Thomas', score: 28, status: 'low', assignedSP: 'Michael Brown', referralPartner: 'Robert Thompson', lastAssessmentDate: '2026-01-18', nextReviewDate: '2027-01-18' },
    { id: '17', clientId: '17', clientName: 'Kevin Harris', score: 92, status: 'high', assignedSP: 'Sarah Johnson', referralPartner: 'James Wilson', lastAssessmentDate: '2026-01-20', nextReviewDate: '2027-01-20' },
    { id: '18', clientId: '18', clientName: 'Nancy Martin', score: 54, status: 'medium', assignedSP: 'John Smith', referralPartner: 'Linda Parker', lastAssessmentDate: '2026-01-22', nextReviewDate: '2027-01-22' },
    { id: '19', clientId: '19', clientName: 'Steven Garcia', score: 42, status: 'medium', assignedSP: 'Emily Davis', referralPartner: 'Sandra Martinez', lastAssessmentDate: '2026-01-24', nextReviewDate: '2027-01-24' },
    { id: '20', clientId: '20', clientName: 'Karen Young', score: 68, status: 'medium', assignedSP: 'Michael Roberts', referralPartner: 'None', lastAssessmentDate: '2026-01-25', nextReviewDate: '2027-01-25' },
    { id: '21', clientId: '21', clientName: 'Edward King', score: 84, status: 'high', assignedSP: 'Jennifer Davis', referralPartner: 'Robert Thompson', lastAssessmentDate: '2026-01-26', nextReviewDate: '2027-01-26' },
    { id: '22', clientId: '22', clientName: 'Ruth Lee', score: 36, status: 'low', assignedSP: 'John Smith', referralPartner: 'James Wilson', lastAssessmentDate: '2026-01-27', nextReviewDate: '2027-01-27' },
    { id: '23', clientId: '23', clientName: 'Donald Scott', score: 78, status: 'high', assignedSP: 'Michael Brown', referralPartner: 'Linda Parker', lastAssessmentDate: '2026-01-28', nextReviewDate: '2027-01-28' },
    { id: '24', clientId: '24', clientName: 'Helen Adams', score: 44, status: 'medium', assignedSP: 'Emily Davis', referralPartner: 'None', lastAssessmentDate: '2026-01-29', nextReviewDate: '2027-01-29' },
    { id: '25', clientId: '25', clientName: 'George Baker', score: 88, status: 'high', assignedSP: 'Sarah Johnson', referralPartner: 'Sandra Martinez', lastAssessmentDate: '2026-01-30', nextReviewDate: '2027-01-30' },
];

export const mockFeatures = [
    { id: '1', name: 'CRM Access', allocatedLicenses: 50, usedLicenses: 32, billingType: 'monthly' as const, amount: 29.99, isActive: true },
    { id: '2', name: 'Analytics Pro', allocatedLicenses: 25, usedLicenses: 18, billingType: 'annually' as const, amount: 299.99, isActive: true },
    { id: '3', name: 'Document Manager', allocatedLicenses: 40, usedLicenses: 35, billingType: 'monthly' as const, amount: 19.99, isActive: true },
    { id: '4', name: 'Client Portal', allocatedLicenses: 100, usedLicenses: 67, billingType: 'monthly' as const, amount: 49.99, isActive: true },
    { id: '5', name: 'Risk Assessment', allocatedLicenses: 30, usedLicenses: 22, billingType: 'annually' as const, amount: 199.99, isActive: false },
];

export const mockOrganizations = [
    { id: '1', name: 'Acme Financial Services', type: 'Enterprise', startDate: '2024-01-15', endDate: '2025-01-15', isActive: true, features: [...mockFeatures], assignedSP: 'Sarah Johnson', referralPartner: 'James Wilson' },
    { id: '2', name: 'Global Wealth Management', type: 'Professional', startDate: '2024-03-01', endDate: '2025-03-01', isActive: true, features: [...mockFeatures], assignedSP: 'John Smith', referralPartner: 'Linda Parker' },
    { id: '3', name: 'Premier Investment Group', type: 'Enterprise', startDate: '2023-11-10', endDate: '2024-11-10', isActive: false, features: [...mockFeatures], assignedSP: 'Michael Chen', referralPartner: 'Robert Thompson' },
    { id: '4', name: 'Secure Financial Partners', type: 'Enterprise', startDate: '2024-05-20', endDate: '2025-05-20', isActive: true, features: [...mockFeatures], assignedSP: 'Emily Davis', referralPartner: 'Linda Parker' },
    { id: '5', name: 'Wealthcret Capital', type: 'Professional', startDate: '2024-06-15', endDate: '2025-06-15', isActive: true, features: [...mockFeatures], assignedSP: 'Sarah Johnson', referralPartner: 'James Wilson' },
];

export const mockTickets: Ticket[] = [
    {
        id: '1',
        organizationId: 'org-1',
        organizationName: 'Acme Financial Services',
        title: 'Issue with portfolio access',
        description: 'Unable to view recent transactions in the portfolio dashboard',
        status: 'in-progress',
        priority: 'high',
        createdBy: 'John Anderson',
        assignedTo: 'Sarah Mitchell',
        createdAt: '2025-12-08T10:30:00Z',
        messages: [
            { id: 'm1', ticketId: '1', sender: 'John Anderson', message: 'I cannot access my portfolio transactions from last week.', timestamp: '2025-12-08T10:30:00Z' },
            { id: 'm2', ticketId: '1', sender: 'Sarah Mitchell', message: 'Thank you for reporting this. I am looking into it now.', timestamp: '2025-12-08T11:15:00Z' },
        ],
    },
    {
        id: '2',
        organizationId: 'org-2',
        organizationName: 'Global Wealth Management',
        title: 'Request for tax documents',
        description: 'Need year-end tax documentation for filing',
        status: 'open',
        priority: 'medium',
        createdBy: 'Emily Chen',
        createdAt: '2025-12-07T14:20:00Z',
        messages: [
            { id: 'm3', ticketId: '2', sender: 'Emily Chen', message: 'Can you please provide my tax documents for 2024?', timestamp: '2025-12-07T14:20:00Z' },
        ],
    },
];

export const mockTeamMembers: TeamMember[] = [
    { id: '1', name: 'Sarah Mitchell', email: 'sarah.mitchell@wealthcret.com', role: 'Senior Financial Advisor', roles: ['2', '4'], joinDate: '2023-03-15' },
    { id: '2', name: 'Michael Roberts', email: 'michael.roberts@wealthcret.com', role: 'Financial Advisor', roles: ['2'], joinDate: '2023-07-20' },
    { id: '3', name: 'Jennifer Davis', email: 'jennifer.davis@wealthcret.com', role: 'Compliance Officer', roles: ['1', '2'], joinDate: '2023-05-10' },
    { id: '4', name: 'Robert Wilson', email: 'robert.wilson@wealthcret.com', role: 'Support Specialist', roles: ['4'], joinDate: '2023-01-12' },
    { id: '5', name: 'Emily Brown', email: 'emily.brown@wealthcret.com', role: 'Admin Assistant', roles: ['1'], joinDate: '2023-09-05' },
];

export const mockDocuments = [
    { id: '1', clientId: '1', name: 'Investment Agreement 2025', type: 'Agreement', status: 'approved', uploadDate: '2025-11-15' },
    { id: '2', clientId: '1', name: 'Tax Documents Q4 2024', type: 'Tax', status: 'approved', uploadDate: '2025-11-20' },
    { id: '3', clientId: '2', name: 'Onboarding Forms', type: 'Legal', status: 'pending', uploadDate: '2025-12-01' },
];

export const mockActivities = [
    { id: '1', clientId: '1', title: 'Portfolio Review Meeting', description: 'Discussed Q4 performance and rebalancing strategy', meetType: 'physical', date: '2025-12-05', createdBy: 'Sarah Mitchell' },
    { id: '2', clientId: '1', title: 'Follow-up Call', description: 'Quick check-in regarding recent market movements', meetType: 'call', date: '2025-12-08', createdBy: 'Sarah Mitchell' },
    { id: '3', clientId: '2', title: 'Onboarding Session', description: 'Introductory session with new client', meetType: 'physical', date: '2025-12-10', createdBy: 'John Smith' },
];

export const mockOrganizationRequests: OrganizationRequest[] = [
    { id: '1', organizationName: 'First Capital Advisors', requestType: 'service_provider', contactPerson: 'Alice Green', email: 'alice@firstcapital.com', phone: '+1 555-0101', status: 'pending', requestDate: '2025-12-10', description: 'New advisor firm onboarding' },
    { id: '2', organizationName: 'Pacific Wealth Partners', requestType: 'referral_partner', contactPerson: 'Bob White', email: 'bob@pacificwealth.com', phone: '+1 555-0202', status: 'approved', requestDate: '2025-12-05', description: 'Strategic referral partnership' },
];

export const mockServiceRequests: ServiceRequest[] = [
    { id: '1', serviceName: 'Portfolio Audit', clientId: '1', clientName: 'John Anderson', status: 'pending', requestDate: '2025-12-11', priority: 'high' },
    { id: '2', serviceName: 'Tax Optimization', clientId: '2', clientName: 'Emily Chen', status: 'assigned', requestDate: '2025-12-09', priority: 'medium' },
];

export const mockNews: NewsItem[] = [
    { id: '1', title: 'Federal Reserve Signals Rate Cuts in 2026', description: 'The Federal Reserve announced today that it is considering interest rate reductions in early 2026.', domain: 'finance', date: '2025-12-09' },
    { id: '2', title: 'Tech Stocks Rally on Strong Q4 Earnings', description: 'Major technology companies reported better-than-expected Q4 earnings, driving the NASDAQ to new highs.', domain: 'markets', date: '2025-12-08' },
];

export const mockMappings: CustomerMapping[] = [
    {
        id: '1',
        customerName: 'ABC Financial Services',
        externalId: 'EXT-2024-001',
        internalId: 'INT-001234',
        system: 'Salesforce',
        status: 'active',
        lastSync: '2025-01-08 14:30',
        serviceProvider: 'John Smith',
        email: 'contact@abcfinancial.com',
        mobile: '+1 (555) 123-4567',
        services: ['1', '2'],
        referralPartner: 'James Wilson',
    },
    {
        id: '2',
        customerName: 'Global Wealth Management',
        externalId: 'EXT-2024-002',
        internalId: 'INT-001235',
        system: 'HubSpot',
        status: 'active',
        lastSync: '2025-01-08 12:15',
        serviceProvider: 'Sarah Johnson',
        email: 'info@globalwealth.com',
        mobile: '+1 (555) 234-5678',
        services: ['3', '4'],
        referralPartner: 'Linda Parker',
    },
    {
        id: '3',
        customerName: 'Premier Investment Group',
        externalId: 'EXT-2024-003',
        internalId: 'INT-001236',
        system: 'Salesforce',
        status: 'pending',
        lastSync: '2025-01-07 18:45',
        serviceProvider: 'Michael Chen',
        email: 'support@premierinvest.com',
        mobile: '+1 (555) 345-6789',
        services: ['1', '3', '5'],
        referralPartner: 'James Wilson',
    },
    {
        id: '4',
        customerName: 'Secure Financial Partners',
        externalId: 'EXT-2024-004',
        internalId: 'INT-001237',
        system: 'Microsoft Dynamics',
        status: 'active',
        lastSync: '2025-01-06 09:20',
        serviceProvider: 'Emily Davis',
        email: 'admin@securefp.com',
        mobile: '+1 (555) 456-7890',
        services: ['2', '6'],
    },
];

export const mockLicenses: License[] = [
    { id: '1', featureName: 'CRM Access', name: 'CRM Access', allocatedLicenses: 50, total: 50, usedLicenses: 32, used: 32, billingType: 'monthly', amount: 29.99, isActive: true },
    { id: '2', featureName: 'Analytics Pro', name: 'Analytics Pro', allocatedLicenses: 25, total: 25, usedLicenses: 18, used: 18, billingType: 'annually', amount: 299.99, isActive: true },
    { id: '3', featureName: 'Document Manager', name: 'Document Manager', allocatedLicenses: 40, total: 40, usedLicenses: 35, used: 35, billingType: 'monthly', amount: 19.99, isActive: true },
    { id: '4', featureName: 'Client Portal', name: 'Client Portal', allocatedLicenses: 100, total: 100, usedLicenses: 67, used: 67, billingType: 'monthly', amount: 49.99, isActive: true },
    { id: '5', featureName: 'Risk Assessment', name: 'Risk Assessment', allocatedLicenses: 30, total: 30, usedLicenses: 22, used: 22, billingType: 'annually', amount: 199.99, isActive: false },
];

export const mockBackofficeTeamMembers: TeamMember[] = [
    {
        id: '1',
        name: 'Sarah Mitchell',
        email: 'sarah.mitchell@wealthcret.com',
        phone: '+1 (555) 123-4567',
        role: 'Team Lead',
        roles: ['1', '2'],
        joinDate: '2024-01-15',
        assignedLicenses: ['1', '2', '4'],
        assignedSP: 'Sarah Johnson',
        referralPartner: 'James Wilson'
    },
    {
        id: '2',
        name: 'Michael Roberts',
        email: 'michael.roberts@wealthcret.com',
        phone: '+1 (555) 234-5678',
        role: 'Senior Advisor',
        roles: ['2'],
        joinDate: '2024-03-01',
        assignedLicenses: ['1', '3'],
        assignedSP: 'John Smith',
        referralPartner: 'Linda Parker'
    },
    {
        id: '3',
        name: 'Emily Wong',
        email: 'emily.wong@wealthcret.com',
        phone: '+1 (555) 345-6789',
        role: 'Advisor',
        roles: ['2', '4'],
        joinDate: '2023-11-10',
        assignedLicenses: ['4', '5'],
        assignedSP: 'Michael Chen',
        referralPartner: 'James Wilson'
    },
];

